spring.application.name=CashCard

debug=true
# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://db.muztqmukdwqagdqjvzmi.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Sport13051905!!
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA/Hibernate (opcional, para criar/atualizar tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
